
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.dah.camel.route.webservice;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2019-07-12T09:08:06.271+08:00
 * Generated source version: 3.0.16
 * 用于客户端（TestClient）
 */



@WebService(
                      serviceName = "CalculatorImplService",
                      portName = "CalculatorImplPort",
                      targetNamespace = "http://webservice.route.camel.dah.com/",
                      wsdlLocation = "http://127.0.0.1:9902/ws/calc?wsdl",
                      endpointInterface = "com.dah.camel.route.webservice.Calculator")
                      
public class CalculatorImplPortImpl implements Calculator {

    private static final Logger LOG = Logger.getLogger(CalculatorImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.dah.camel.route.webservice.client.Calculator#subtract(java.lang.Integer arg0, java.lang.Integer arg1)*
     */
    public Long subtract(Integer arg0, Integer arg1) {
        LOG.info("Executing operation subtract");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            Long _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.dah.camel.route.webservice.client.Calculator#multiply(java.lang.Integer arg0, java.lang.Integer arg1)*
     */
    public Long multiply(Integer arg0, Integer arg1) {
        LOG.info("Executing operation multiply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            Long _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.dah.camel.route.webservice.client.Calculator#add(java.lang.Integer arg0, java.lang.Integer arg1)*
     */
    public Long add(Integer arg0, Integer arg1) {
        LOG.info("Executing operation add");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            Long _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.dah.camel.route.webservice.client.Calculator#getVersion(java.lang.String arg0)*
     */
    public String getVersion(String arg0) {
        LOG.info("Executing operation getVersion");
        System.out.println(arg0);
        try {
            String _return = "";
            return _return + "123456";
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
